name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: valgrind
      run: |
       sudo apt-get -y install valgrind
       valgrind -v --leak-check=full --show-leak-kinds=all ./bin
           
    - name: make test
      run : |
               make test -C MiniProject_C/3_Implementation/
               valgrind ./MiniProject_C/3_Implementation/build/Test_quiz.out
       
         
        
